import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Components from './Components'

export default function Home() {
  return (
    <>    <div className={styles.container}>
      <Head>
        <title>My Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
     <div className={styles.div1}>
        <p> Simple Calculator</p>

     </div>
      <div className={styles.div2}>
             <Components/>
      </div>

    </div>
    </>

  )
}
